remote = false

[models]

[models.one]
name = "openai-community/gpt2"
chat = false

[models.one.rename]
transformer = "model"
h = "layers"
c_proj = "o_proj"

[models.one.config]
n_heads = 12
n_layers = 12